name: Run SOAPUI Project on Multiple OS 

on:
  workflow_dispatch:
  # push:
  #   branches:
  #     - main
  # pull_request:
  schedule:
    - cron: '15 16 * * *'

jobs:
  soapui-tests:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest, macos-latest]

    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      
      - name: Set up JDK
        uses: actions/setup-java@v2
        with:
          java-version: '17'
      
      - name: Install SoapUI
        run: |
          echo "Installing SoapUI..."
          if [ ${{ runner.os }} == 'Linux' ]; then
            wget https://downloads.sourceforge.net/project/soapui/soapui/5.6.0/SoapUI-5.6.0-linux-bin.tar.gz
            tar -xzf SoapUI-5.6.0-linux-bin.tar.gz
            mv SoapUI-5.6.0 /opt/soapui
          elif [ ${{ runner.os }} == 'Windows' ]; then
            echo "Windows installation instructions needed."
          else
            echo "Mac installation instructions needed."
          fi

      - name: Run SoapUI Tests
        run: |
          /opt/soapui/bin/soapui.sh -a -r -j -f results -t CountryInfoService-soapui-project.xml
        env:
          SOAPUI_HOME: /opt/soapui

      - name: Generate JUnit Report
        run: |
          # You may need to adjust this based on how your results are structured
          echo "Generating JUnit report..."
          mkdir -p junit-results
          cp results/*.xml junit-results/
          
      - name: Convert JUnit XML to HTML Report
        run: |
          echo "Converting JUnit XML to HTML..."
          # Install an HTML report generator, e.g., junit2html
          pip install junit2html
          junit2html junit-results/*.xml -o junit-results/report.html
          
      - name: Upload Report
        uses: actions/upload-artifact@v2
        with:
          name: soapui-test-report
          path: junit-results/report.html
