name: Run SOAPUI Project on Windows

on:
  workflow_dispatch:
  schedule:
    - cron: '20 16 * * *'

jobs:
  soapui:
    runs-on: windows-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        
      - name: Install WSL and Ubuntu
        run: |
          wsl --install -d Ubuntu
          wsl --set-default-version 2
        shell: powershell

      - name: Install SoapUI on Linux
        run: |
          wsl wget https://dl.eviware.com/soapuios/5.7.2/SoapUI-5.7.2-linux-bin.tar.gz
          wsl tar -xzf SoapUI-5.7.2-linux-bin.tar.gz -C /opt/
          wsl rm SoapUI-5.7.2-linux-bin.tar.gz

      - name: Run SoapUI Tests
        run: |
          wsl /opt/SoapUI-5.7.2/bin/testrunner.sh -s "CountryInfoServiceSoapBinding TestSuite" -r -a -f results /path/to/CountryInfoService-soapui-project.xml

      - name: Upload Test Reports
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: soapui-test-reports
          path: results
