name: Run SOAPUI Project on Ubuntu 

on:
  workflow_dispatch:
  # push:
  #   branches:
  #     - main
  # pull_request:
  schedule:
    - cron: '15 16 * * *'

jobs:
  soapui:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up JDK
        uses: actions/setup-java@v4
        with:
          java-version: '11'
          distribution: 'temurin'

      - name: Install SoapUI
        run: |
          echo "Installing SoapUI..."
          wget https://dl.eviware.com/soapuios/5.7.2/SoapUI-5.7.2-linux-bin.tar.gz
          tar -xzf SoapUI-5.7.2-linux-bin.tar.gz
          sudo mv SoapUI-5.7.2 /opt/soapui
          rm SoapUI-5.7.2-linux-bin.tar.gz

      - name: Install Xvfb
        run: sudo apt-get install -y xvfb

      - name: Start Xvfb
        run: |
          export DISPLAY=:99
          Xvfb :99 -screen 0 1920x1080x24 &
          sleep 3

      - name: Run SoapUI Tests with testrunner
        run: |
          set -e  # Stop the script on any error
          export SOAPUI_HOME=/opt/soapui
          export DISPLAY=:99
          chmod +x $SOAPUI_HOME/bin/testrunner.sh
          mkdir -p results
          $SOAPUI_HOME/bin/testrunner.sh -s"CountryInfoServiceSoapBinding TestSuite" -r -a -f results CountryInfoService-soapui-project.xml
        env:
          JAVA_HOME: /opt/hostedtoolcache/Java_Temurin-Hotspot_jdk/17.0.12-7/x64
          JAVA_HOME_17_X64: /opt/hostedtoolcache/Java_Temurin-Hotspot_jdk/17.0.12-7/x64

      - name: Archive Test Results
        if: always()
        uses: actions/upload-artifact@v3
        with:
          name: soapui-test-reports
          path: results
