name: Run SOAPUI Project on Windows

on:
  workflow_dispatch:
  schedule:
    - cron: '20 16 * * *'

jobs:
  soapui:
    runs-on: windows-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Install SoapUI on Windows
        run: |
          Invoke-WebRequest https://dl.eviware.com/soapuios/5.7.2/SoapUI-5.7.2-windows-bin.zip -OutFile SoapUI-win.zip
          Expand-Archive -Path SoapUI-win.zip -DestinationPath C:\SoapUI
          Remove-Item SoapUI-win.zip
          # Set the SOAPUI_HOME environment variable
          echo "SOAPUI_HOME=C:\\SoapUI" >> $GITHUB_ENV
          
      - name: Verify SOAPUI_HOME
        run: |
          Write-Host "SOAPUI_HOME: $Env:SOAPUI_HOME"

      - name: Run SoapUI Tests
        run: |
          mkdir results
          Write-Host "SOAPUI_HOME: $Env:SOAPUI_HOME"
          & "$Env:SOAPUI_HOME\bin\testrunner.bat" -s "CountryInfoServiceSoapBinding TestSuite" -r -a -f results CountryInfoService-soapui-project.xml
        shell: pwsh

      - name: Upload Test Reports
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: soapui-test-reports-windows
          path: results
